### ISSUE TITLE
Trailer 

### ISSUE THREAD

**Issue by intwinsGarv** [Zazzop/Apex-Legends#1]
There is a bug , whenever i open my game it always shows the trailer , which is kinda annoying . plz fix it

**Comment by Zazzop** [comment]
**Fix #1:**  
type -dev and -novid in launchoptions 
![image](https://user-images.githubusercontent.com/24703788/135755638-aec3fd38-02b6-453b-b1ee-981a4ca47532.png)

**Fix #2:**  
             1. Go to C:\Users\ *username* \Saved Games\Respawn\Apex\profile.  
             2. Right click the CFG file titled "profile" and click properties. 
             3. Uncheck the read-only box. Apply changes and click okay. 
             4. Then the next time you open the game, it will play the video and remember its been played, then not play it again.

**Comment by intwinsGarv** [comment]
i already tried the both fixes but none of them worked  .. but when i was checking the auto exec i found out that this "intro_viewed "0" " was causing it . can u plz confirm , that is it ok to delete it ?

**Comment by Zazzop** [comment]
> i already tried the both fixes but none of them worked .. but when i was checking the auto exec i found out that this "intro_viewed "0" " was causing it . can u plz confirm , that is it ok to delete it ?

Maybe u can try it, but it works well for me. You can uncheck the read-only box in  settings.txt and videosettings.txt.

Fix #3: 
             1. Go to C:\Program Files (x86)\Origin Games\Apex\media
             2. Rename startupvids.txt to any other name ex. startupvids2.txt
             3. Launch the game

**Comment by intwinsGarv** [comment]
Thank you for helping
